DELETE FROM `unr_players` ;
INSERT INTO `unr_players` (`id`, `name`, `password`, `email`, `active`, `webadmin`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'admin@site.com', 1, 1),
(2, 'test', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0);

DELETE FROM `unr_achiev`;
INSERT INTO `unr_achiev` (`id`, `name`, `description`, `count`, `type`) VALUES
(1, 'langA_WarBond', 'langAD_WarBond', 125000, 'money_t'),
(2, 'langA_RepeatOffender', 'langAD_RepeatOffender',  1, 'dominate_o'),
(3, 'langA_MagicBullet', 'langAD_MagicBullet',  1, 'kill_l'),
(4, 'langA_PositionStrength', 'langAD_PositionStrength',  1, 'dominate_m'),
(5, 'langA_EyeEye', 'langAD_EyeEye',  1, 'kill_s'),
(6, 'langA_Insurgent', 'langAD_Insurgent',  1, 'dominate_m'),
(7, 'langA_ExcessiveBrutality', 'langAD_ExcessiveBrutality',  4, 'dominate_d'),
(8, 'langA_Decimator', 'langAD_Decimator',  10, 'dominate_o'),
(9, 'langA_HetTrick', 'langAD_HetTrick',  3, 'dominate_t'),
(10, 'langA_SavingAmm', 'langAD_SavingAmm',  1, 'kill_d'),
(11, 'langA_Corpseman', 'langAD_Corpseman',  500, 'kill_e'),
(12, 'langA_DeathSky', 'langAD_DeathSky',  1, 'airkill_u'),
(13, 'langA_SpoilsWar', 'langAD_SpoilsWar',  2500000, 'money_t'),
(14, 'langA_ArtWar', 'langAD_ArtWar',  100, 'spray'),
(15, 'langA_DontTouch', 'langAD_DontTouch',  20, 'dominate_m'),
(16, 'langA_AerialNecrobatics', 'langAD_AerialNecrobatics',  1, 'airkill_b'),
(17, 'langA_GodWar', 'langAD_GodWar',  10000, 'kill_e'),
(18, 'langA_BunnyHunt', 'langAD_BunnyHunt',  1, 'airkill_e'),
(19, 'langA_HelloGuys', 'langAD_HelloGuys',  5, 'flash_t'),
(20, 'langA_BloodMoney', 'langAD_BloodMoney',  50000000, 'money_t'),
(21, 'langA_TalkativePlayer', 'langAD_TalkativePlayer',  1000, 'say'),
(22, 'langA_DayYouth', 'langAD_DayYouth',  1000, 'spray'),
(23, 'langA_RichPlayer', 'langAD_RichPlayer',  100000, 'money_b'),
(24, 'langA_HeadShred', 'langAD_HeadShred',  5, 'headshoots_in_round'),
(25, 'langA_Primer', 'langAD_Primer',  1, '95dmg'),
(26, 'langA_FinishingSchooled', 'langAD_FinishingSchooled',  1, '5dmg'),
(27, 'langA_MadProps', 'langAD_MadProps',  10, 'break_in_round'),
(28, 'langA_NewbWorld', 'langAD_NewbWorld',  10, 'win_round'),
(29, 'langA_ProMoted', 'langAD_ProMoted',  200, 'win_round'),
(30, 'langA_LeetMen', 'langAD_LeetMen',  5000, 'win_round'),
(31, 'langA_SecondNone', 'langAD_SecondNone',  1, '1sek_defusing'),
(32, 'langA_Boomala', 'langAD_Boomala',  100, 'bomb_plant'),
(33, 'langA_HurtBlocker', 'langAD_HurtBlocker',  100, 'bomb_defuse'),
(34, 'langA_Veteran', 'langAD_Veteran',  100, 'de_dust2_win_round'),
(35, 'langA_Destroyer', 'langAD_Destroyer',  500, 'break'),
(36, 'langA_VeteranNuke', 'langAD_VeteranNuke',  100, 'de_nuke_win_round'),
(37, 'langA_VeteranTemple', 'langAD_VeteranTemple',  100, 'deathrun_temple_win_round'),
(38, 'langA_VeteranSki2', 'langAD_VeteranSki2',  100, 'surf_ski_2_win_round'),
(39, 'langA_VeteranRooftops', 'langAD_VeteranRooftops',  100, 'awp_rooftops_win_round'),
(40, 'langA_VeteranFloppytown', 'langAD_VeteranFloppytown',  100, 'hns_floppytown_win_round'),
(41, 'langA_VeteranOIL', 'langAD_VeteranOIL',  1000000, 'money_t'),
(42, 'langA_Halloween', 'langAD_Halloween',  20, 'collect_halloween_present');

DELETE FROM `lang`;
insert  into `lang`(`lang`,`var`,`value`) values
('ru','langA_WarBond','Военные Облигации'),
('ru','langA_RepeatOffender','Рецидивист'),
('ru','langA_MagicBullet','Волшебная Пуля'),
('ru','langA_PositionStrength','С позиции силы'),
('ru','langA_EyeEye','Глаза в глаза'),
('ru','langA_Insurgent','Боевик'),
('ru','langA_ExcessiveBrutality','Чрезмерная Жестокость'),
('ru','langA_Decimator','Дециматор'),
('ru','langA_HetTrick','Хет-трик'),
('ru','langA_SavingAmm','Экономия патронов'),
('ru','langA_Corpsman','Санитар'),
('ru','langA_DeathSky','Смерть с неба'),
('ru','langA_SpoilsWar','Трофеи войны'),
('ru','langA_ArtWar','Искусство войны'),
('ru','langA_DontTouch','Не тронь меня!'),
('ru','langA_AerialNecrobatics','Воздушный Necrobatics'),
('ru','langA_GodWar','Бог войны'),
('ru','langA_BunnyHunt','Банни Хант'),
('ru','langA_HelloGuys','Привет, Ребята'),
('ru','langA_BloodMoney','Кровавые Деньги'),
('ru','langA_TalkativePlayer','Общительный игрок'),
('ru','langA_DayYouth','День молодежи'),
('ru','langA_RichPlayer','Богатый игрок'),
('ru','langA_HeadShred','Глава Лоскуток Выкупа'),
('ru','langA_Primer','Праймер'),
('ru','langA_FinishingSchooled','Отделка Вышколены'),
('ru','langA_MadProps','Баальшой Респект'),
('ru','langA_NewbWorld','Ньют Мировой Порядок'),
('ru','langA_ProMoted','Поощрятель'),
('ru','langA_LeetMen','Leet мужчина'),
('ru','langA_SecondNone','Второй нет'),
('ru','langA_Boomala','Boomala Boomala'),
('ru','langA_HurtBlocker','Блокиратор Больно'),
('ru','langA_Veteran','Ветеран карты Dust2'),
('ru','langA_Destroyer','Разрушитель'),
('ru','langA_VeteranNuke','Ветеран карты Nuke'),
('ru','langA_VeteranTemple','Ветеран карты Temple'),
('ru','langA_VeteranSki2','Ветеран карты ski 2'),
('ru','langA_VeteranRooftops','Ветеран карты rooftops'),
('ru','langA_VeteranFloppytown','Ветеран карты floppytown'),
('ru','langA_VeteranOIL','НЕФТЬ! Я БОГАТ!'),
('ru','langA_Halloween','Хэллоуин время!'),
('ru','langAD_WarBond','Заработать $125,000'),
('ru','langAD_RepeatOffender','Доминировать над вражеским игроком'),
('ru','langAD_MagicBullet','Убить врага последним патроном в магазине'),
('ru','langAD_PositionStrength','Убить противника, над которым вы уже доминируете'),
('ru','langAD_EyeEye','Убить из снайперской винтовки вражеского снайпера'),
('ru','langAD_Insurgent','Убить вражеского игрока, который над вами доминирует'),
('ru','langAD_ExcessiveBrutality','Убить вражеского игрока еще 4 раза, когда вы уже доминируете над ним'),
('ru','langAD_Decimator','Доминировать над 10 вражескими игроками'),
('ru','langAD_HetTrick','Доминировать одновременно над тремя вражескими игроками'),
('ru','langAD_SavingAmm','Убить двух противников одной пулей'),
('ru','langAD_Corpseman','Убить 500 врагов'),
('ru','langAD_DeathSky','Убить врага, находясь в воздухе'),
('ru','langAD_SpoilsWar','Заработать $2,500,000'),
('ru','langAD_ArtWar','Нарисовать 100 рисунков'),
('ru','langAD_DontTouch','Убить 20 вражеских игроков, которые доминируют над вами'),
('ru','langAD_AerialNecrobatics','Находясь в воздухе, убить врага, тоже находящегося в воздухе'),
('ru','langAD_GodWar','Убить 10000 врагов'),
('ru','langAD_BunnyHunt','Убить врага, находящегося в воздухе'),
('ru','langAD_HelloGuys','Ослепить товарищей 5 раз'),
('ru','langAD_BloodMoney','Заработать $50,000,000'),
('ru','langAD_TalkativePlayer','Написать в чат 1000 сообщений'),
('ru','langAD_DayYouth','Нарисовать 1000 рисунков'),
('ru','langAD_RichPlayer','Потратить $100,000'),
('ru','langAD_HeadShred','Убить 5 врагов выстрелами в голову за один раунд'),
('ru','langAD_Primer','Нанести 95% урона врагу, которого затем убивает другой игрок'),
('ru','langAD_FinishingSchooled','Убить врага, который доведен до уровня мнее 5% здоровья другим игроком'),
('ru','langAD_MadProps','Сломать 10 предметов за один раунд'),
('ru','langAD_NewbWorld','Выиграть 10 раундов'),
('ru','langAD_ProMoted','Выиграть 200 раундов'),
('ru','langAD_LeetMen','Выиграть 5000 раундов'),
('ru','langAD_SecondNone','Успешно обезвредить бомбу менее чем за одну секунду до взрыва'),
('ru','langAD_Boomala','Установить 100 бомб'),
('ru','langAD_HurtBlocker','Обезвредить 100 бомб'),
('ru','langAD_Veteran','Выиграть 100 раундов на карте de_dust2'),
('ru','langAD_Destroyer','Сломать 500 предметов'),
('ru','langAD_VeteranNuke','Выиграть 100 раундов на карте de_nuke'),
('ru','langAD_VeteranTemple','Выиграть 100 раундов на карте deathrun_temple'),
('ru','langAD_VeteranSki2','Выиграть 100 раундов на карте surf_ski_2'),
('ru','langAD_VeteranRooftops','Выиграть 100 раундов на карте awp_rooftops'),
('ru','langAD_VeteranFloppytown','Выиграть 100 раундов на карте hns_floppytown'),
('ru','langAD_VeteranOIL','Заработать $1,000,000'),
('ru','langAD_Halloween','Собрать 20 мешков с подарками в период с 29.10 по 3.11'),
('en','langA_WarBond','War Bonds'),
('en','langA_RepeatOffender','Repeat Offender'),
('en','langA_MagicBullet','Magic Bullet'),
('en','langA_PositionStrength','From a position of strength'),
('en','langA_EyeEye','Eye to Eye'),
('en','langA_Insurgent','Insurgent'),
('en','langA_ExcessiveBrutality','Excessive Brutality'),
('en','langA_Decimator','Decimator'),
('en','langA_HetTrick','A hat-trick'),
('en','langA_SavingAmm','Saving ammunition'),
('en','langA_Corpsman','Corpsman'),
('en','langA_DeathSky','Смерть с неба'),
('en','langA_SpoilsWar','Spoils of War'),
('en','langA_ArtWar','The Art of War'),
('en','langA_DontTouch','Don\'t touch me!'),
('en','langA_AerialNecrobatics','Aerial Necrobatics'),
('en','langA_GodWar','God of War'),
('en','langA_BunnyHunt','Bunny Hunt'),
('en','langA_HelloGuys','Hello Guys'),
('en','langA_BloodMoney','Blood Money'),
('en','langA_TalkativePlayer','A talkative player'),
('en','langA_DayYouth','Youth day'),
('en','langA_RichPlayer','Rich player'),
('en','langA_HeadShred','Head Shred Redemption'),
('en','langA_Primer','Primer'),
('en','langA_FinishingSchooled','Finishing Schooled'),
('en','langA_MadProps','Mad Props'),
('en','langA_NewbWorld','Newb World Order'),
('en','langA_ProMoted','Pro-moted'),
('en','langA_LeetMen','Leet-er of Men'),
('en','langA_SecondNone','Second to None'),
('en','langA_Boomala','Boomala Boomala'),
('en','langA_HurtBlocker','The Hurt Blocker'),
('en','langA_Veteran','Veteran maps Dust2'),
('en','langA_Destroyer','Разрушитель'),
('en','langA_VeteranNuke','Veteran maps Nuke'),
('en','langA_VeteranTemple','Veteran maps Temple'),
('en','langA_VeteranSki2','Veteran maps ski 2'),
('en','langA_VeteranRooftops','Veteran maps rooftops'),
('en','langA_VeteranFloppytown','Veteran maps floppytown'),
('en','langA_VeteranOIL','OIL! I\'M RICH!'),
('en','langA_Halloween','Halloween time!'),
('en','langAD_WarBond','Earn $125,000'),
('en','langAD_RepeatOffender','Dominate an enemy player'),
('en','langAD_MagicBullet','Kill an enemy with the last bullet in the store'),
('en','langAD_PositionStrength','Kill the enemy, over which you already dominate'),
('en','langAD_EyeEye','To kill from a sniper rifle the enemy sniper'),
('en','langAD_Insurgent','Kill an enemy player that is dominating over you'),
('en','langAD_ExcessiveBrutality','Kill an enemy player 4 times when you already dominate it'),
('en','langAD_Decimator','To dominate the 10 enemy players'),
('en','langAD_HetTrick','At the same time to dominate three enemy players'),
('en','langAD_SavingAmm','Kill two enemies with one bullet'),
('en','langAD_Corpseman','Kill 500 enemies'),
('en','langAD_DeathSky','Kill an enemy while in the air'),
('en','langAD_SpoilsWar','Earn $2,500,000'),
('en','langAD_ArtWar','To draw 100 drawings'),
('en','langAD_DontTouch','Kill 20 enemy players that are dominating you'),
('en','langAD_AerialNecrobatics','While in the air, to kill the enemy is also in the air'),
('en','langAD_GodWar','Kill 10,000 enemies'),
('en','langAD_BunnyHunt','Kill the enemy in the air'),
('en','langAD_HelloGuys','Dazzle comrades 5 times'),
('en','langAD_BloodMoney','Earn $50,000,000'),
('en','langAD_TalkativePlayer','Write in the chat 1000 messages'),
('en','langAD_DayYouth','To draw 1,000 drawings'),
('en','langAD_RichPlayer','To spend $100,000'),
('en','langAD_HeadShred','Kill 5 enemies with headshots in a single round'),
('en','langAD_Primer','To inflict 95% damage to enemy that then kills the other player'),
('en','langAD_FinishingSchooled','Kill the enemy that brought to the level of less than 5% health by other player'),
('en','langAD_MadProps','Break 10 objects in a single round'),
('en','langAD_NewbWorld','Win 10 rounds'),
('en','langAD_ProMoted','Win 200 rounds'),
('en','langAD_LeetMen','Win 5,000 rounds'),
('en','langAD_SecondNone','Successfully defuse a bomb in less than one second before the explosion'),
('en','langAD_Boomala','Install 100 bombs'),
('en','langAD_HurtBlocker','Defuse 100 bombs'),
('en','langAD_Veteran','Win 100 rounds on the de_dust2 map'),
('en','langAD_Destroyer','Break 500 objects'),
('en','langAD_VeteranNuke','Win 100 rounds on the de_nuke map'),
('en','langAD_VeteranTemple','Win 100 rounds on the map deathrun_temple'),
('en','langAD_VeteranSki2','Win 100 rounds on the map surf_ski_2'),
('en','langAD_VeteranRooftops','Win 100 rounds on the map awp_rooftops'),
('en','langAD_VeteranFloppytown','Win 100 rounds on the map hns_floppytown'),
('en','langAD_VeteranOIL','To earn $1,000,000'),
('en','langAD_Halloween','Collect 20 bags of gifts in the period from 29.10 till 3.11'),
('ru','langLang_ru','Русский'),
('ru','langLang_en','English'),
('ru','lang_wpn_0',''),
('ru','lang_wpn_1','P228'),
('ru','lang_wpn_2',''),
('ru','lang_wpn_3','SCOUT'),
('ru','lang_wpn_4','HEGRENADE'),
('ru','lang_wpn_5','XM1014'),
('ru','lang_wpn_6','C4'),
('ru','lang_wpn_7','MAC10'),
('ru','lang_wpn_8','AUG'),
('ru','lang_wpn_9','SMOKEGRENADE'),
('ru','lang_wpn_10','ELITE'),
('ru','lang_wpn_11','FIVESEVEN'),
('ru','lang_wpn_12','UMP45'),
('ru','lang_wpn_13','SG550'),
('ru','lang_wpn_14','GALI'),
('ru','lang_wpn_15','FAMAS'),
('ru','lang_wpn_16','USP'),
('ru','lang_wpn_17','GLOCK18'),
('ru','lang_wpn_18','AWP'),
('ru','lang_wpn_19','MP5NAVY'),
('ru','lang_wpn_20','M249'),
('ru','lang_wpn_21','M3'),
('ru','lang_wpn_22','M4A1'),
('ru','lang_wpn_23','TMP'),
('ru','lang_wpn_24','G3SG1'),
('ru','lang_wpn_25','FLASHBANG'),
('ru','lang_wpn_26','DEAGLE'),
('ru','lang_wpn_27','SG552'),
('ru','lang_wpn_28','AK47'),
('ru','lang_wpn_29','KNIFE'),
('ru','lang_wpn_30','P90'),
('ru','lang_wpn_31','VEST'),
('ru','lang_wpn_32','VESTHELM'),
('ru','langTheme_main','Стандарная'),
('ru','langTheme_white','Инвертная'),
('ru','langTheme_image','Картинки'),
('ru','langTheme_null','Пустая'),
('ru','langThemeNotFound','тема не существует'),
('ru','langMain','Главная'),
('ru','lang_home','Начало'),
('ru','lang_achiev','Достижения'),
('ru','lang_ucp','Личный кабинет'),
('ru','lang_logout','Выйти'),
('ru','langTitle','Lonis'),
('ru','lang_admin_achiev','Настройка достижений'),
('ru','lang_admin_lang','Язык'),
('ru','langRegErrors','Произошли следующие ошибки:'),
('ru','langNotInputNick','Вы не ввели ник!'),
('ru','langNotInputPassword','Вы не ввели пароль!'),
('ru','langNotInputMail','Вы не ввели e-mail!'),
('ru','langAlreadyLogin','Вы уже вошли!'),
('ru','langWarning','Внимание!'),
('ru','langUserNotFound','Не найден пользователь с введёнными вами данными!'),
('ru','langName','Имя'),
('ru','langPassword','Пароль'),
('ru','lang_login','Войти'),
('ru','lang_loginReg','Войти/Регистрация'),
('ru','lang_reg','Регистрация'),
('ru','lang_regTitle','Регистрация'),
('ru','langMustLogin','Необходимо войти!'),
('ru','langDataUpdated','Данные успешно обновлены!'),
('ru','langIP','IP'),
('ru','langSteamID','Steam ID'),
('ru','langUpdate','Обновить'),
('ru','langReadme','Бла бла бла'),
('ru','langCurrent','Текущий'),
('ru','langInActive','Учётная запись неактивна!'),
('ru','langAlreadyRegister','Вы уже зарегистрированы!'),
('ru','lang_regSuccess','Вы успешно зарегистрированы! Ссылка для активации отправлена на указанный e-mail'),
('ru','langAlreadyUsed','Такое имя пользователя уже занято!'),
('ru','langEmail','e-mail'),
('ru','langActiveSuccess','Ваша учётная запись успешно активирована!'),
('ru','langActiveError','Неверный либо старый ключ активации!'),
('ru','langActiveMail','Для активации пройдите по следующей ссылке:'),
('ru','lang_sendMailError','Ошибка отправки почты'),
('ru','lang_achievsPlayers','Игроки, выполнившие достижение'),
('ru','lang_achievPlayerTotal','Всего выполнено достижений:'),
('ru','lang_achievsUnlocked','Разблокировано: '),
('ru','langDescription','Описание'),
('ru','langCount','Количество'),
('ru','langType','Тип'),
('ru','langAdd','Добавить'),
('ru','lang_achiev_admin','Управление достижениями'),
('ru','lang_achiev_players','Достижения игроков'),
('ru','langMyAchiev','Мои достижения'),
('ru','langSearch','Поиск'),
('ru','lang_green_chat','Префикс VIP в чате'),
('ru','lang_seeing_list','Список наблюдающих'),
('ru','lang_trail','/trail'),
('ru','lang_whois','Whois'),
('ru','langKzPro','Про'),
('ru','langKzNoob','Новички'),
('ru','langKzAll','Все'),
('ru','langStats','Статистика: '),
('ru','langMap','Карта '),
('ru','langPlayer','Игрок'),
('ru','lang_players','Игроки'),
('ru','langTime','Время'),
('ru','langCp','Чекпоинтов'),
('ru','langGoCp','Телепортов'),
('ru','langWeapon','Оружие'),
('ru','langRecords','Рекордов'),
('ru','langCountry','Страна'),
('ru','langView','подробно...'),
('ru','langRecs','Рекорд'),
('ru','langWorldRecord','Мировой рекорд'),
('ru','langRuRecord','Русский рекорд'),
('ru','langKzNum','Всего'),
('ru','langKzTop1','Первый'),
('ru','langKzNoRec','Не пройденные'),
('ru','langKzRec','Пройденные'),
('ru','langKzStats','KZ Статистика'),
('ru','langDRStats','DR Статистика'),
('ru','langCity','Город'),
('ru','lang_achievCompleted','Выполнил достижений: '),
('ru','langMapCompleted','Прошёл KZ карт: '),
('ru','lang_kz_duels','KZ Дуэль'),
('ru','lang_kz_maps','KZ карты'),
('ru','lang_kz_players','KZ игроки'),
('ru','langWinner','Победитель'),
('ru','langLooser','Проигравший'),
('ru','langWinnerPoint','Очков победителя'),
('ru','langLooserPoint','Очков проигравшего'),
('ru','langMyKz','Мои KZ рекорды'),
('ru','langAuthNickPassword','Ник и пароль'),
('ru','langAuthSteamId','Steam ID'),
('ru','langAuthType','Тип авторизации'),
('ru','langBanned','Вы забанены!!!'),
('ru','langTitleGameAcc','Игровой аккаунт'),
('ru','langTitleSettings','Настройки'),
('ru','langTitlePersonalData','Личные данные'),
('ru','langICQ','ICQ'),
('ru','langAvatar','Аватар'),
('ru','lang_steam_login','Войдите через Steam'),
('ru','langNoSteamLogin','Или заполните форму'),
('ru','lang_setup','Настройка конфига'),
('ru','langSave','Сохранить'),
('ru','langSaved','Сохранено'),
('ru','langReset','Сбросить'),
('ru','langResetDef','Сбросить настройки'),
('ru','langConfirm','Подтвердите действие'),
('ru','lang_timezone','Временная зона'),
('ru','lang_charset','Кодировка'),
('ru','lang_mysql_user','Пользователь базы'),
('ru','lang_mysql_password','Пароль базы'),
('ru','lang_mysql_host','Адрес базы'),
('ru','lang_mysql_db','База'),
('ru','lang_mysql_prefix','Префикс'),
('ru','lang_activateTime','Время активации профиля'),
('ru','lang_baseUrl','Адрес сайта'),
('ru','lang_gravatarSize','Размер аватара'),
('ru','lang_playerPerPage','Игроков на странице'),
('ru','lang_mapsPerPage','Карт на странице'),
('ru','lang_playersPerPage','Игроков на странице KZ'),
('ru','lang_langlist','Список языков (через пробел)'),
('ru','lang_lang','Язык по умолчанию'),
('ru','lang_themelist','Список тем (через пробел)'),
('ru','lang_theme','Тема по умолчанию'),
('ru','lang_cstheme','Тема по умолчанию в CS'),
('ru','lang_email','E-mail'),
('ru','lang_cookieKey','Cookie Ключ'),
('ru','langGenerate','Генерировать'),
('ru','lang_setupGeneral','Основные настройки'),
('ru','lang_setupDb','База данных'),
('ru','lang_setupLang','Язык'),
('ru','langDbTitle','Работа с базой данных'),
('ru','langBase','База'),
('ru','langTables','Таблицы'),
('ru','langData','Данные'),
('ru','langCreate','Создать'),
('ru','langDelete','Удалить'),
('ru','langClear','Очистить'),
('ru','langEdit','Изменить'),
('ru','langDbNotConnect','Нет подключения к базе данных'),
('ru','langDbNotTablesFile','Файл с таблицами не существует'),
('ru','langDbNotDataFile','Файл с данными не существует'),
('ru','langGlobal','Глобальные'),
('ru','langLocal','Локальные'),
('ru','langError','Ошибка'),
('en','langLang_ru','Русский'),
('en','langLang_en','English'),
('en','lang_wpn_0',''),
('en','lang_wpn_1','P228'),
('en','lang_wpn_2',''),
('en','lang_wpn_3','SCOUT'),
('en','lang_wpn_4','HEGRENADE'),
('en','lang_wpn_5','XM1014'),
('en','lang_wpn_6','C4'),
('en','lang_wpn_7','MAC10'),
('en','lang_wpn_8','AUG'),
('en','lang_wpn_9','SMOKEGRENADE'),
('en','lang_wpn_10','ELITE'),
('en','lang_wpn_11','FIVESEVEN'),
('en','lang_wpn_12','UMP45'),
('en','lang_wpn_13','SG550'),
('en','lang_wpn_14','GALI'),
('en','lang_wpn_15','FAMAS'),
('en','lang_wpn_16','USP'),
('en','lang_wpn_17','GLOCK18'),
('en','lang_wpn_18','AWP'),
('en','lang_wpn_19','MP5NAVY'),
('en','lang_wpn_20','M249'),
('en','lang_wpn_21','M3'),
('en','lang_wpn_22','M4A1'),
('en','lang_wpn_23','TMP'),
('en','lang_wpn_24','G3SG1'),
('en','lang_wpn_25','FLASHBANG'),
('en','lang_wpn_26','DEAGLE'),
('en','lang_wpn_27','SG552'),
('en','lang_wpn_28','AK47'),
('en','lang_wpn_29','KNIFE'),
('en','lang_wpn_30','P90'),
('en','lang_wpn_31','VEST'),
('en','lang_wpn_32','VESTHELM'),
('en','langTheme_main','Standart'),
('en','langTheme_white','Invert'),
('en','langTheme_image','Images'),
('en','langTheme_null','Empty'),
('en','langThemeNotFound','Theme not found'),
('en','langMain','Main'),
('en','lang_home','Home'),
('en','lang_achiev','Achievs'),
('en','lang_ucp','Personal account'),
('en','lang_logout','Logout'),
('en','langTitle','Lonis'),
('en','lang_admin_achiev','Setup achiev'),
('en','lang_admin_lang','Dictonaries'),
('en','langRegErrors','Failed with the following error:'),
('en','langNotInputNick','You did not enter nick!'),
('en','langNotInputPassword','You have not entered a password!'),
('en','langNotInputMail','You have not entered e-mail!'),
('en','langAlreadyLogin','You already entered!'),
('en','langWarning','Warning!'),
('en','langUserNotFound','Not found user entered data!'),
('en','langName','Name'),
('en','langPassword','Password'),
('en','lang_login','Login'),
('en','lang_loginReg','Login/Register'),
('en','lang_reg','Register'),
('en','lang_regTitle','Registration'),
('en','lang_achiev_players','Achievs players'),
('en','langMustLogin','You need to login!'),
('en','langDataUpdated','Data updated successfully!'),
('en','langIP','IP'),
('en','langSteamID','Steam ID'),
('en','langUpdate','Update'),
('en','langReadme','Bla Bla Bla'),
('en','langCurrent','Current'),
('en','langInActive','Account inactive!'),
('en','langAlreadyRegister','You are already registered!'),
('en','lang_regSuccess','You have successfully registered! Activation link sent to your e-mail'),
('en','langAlreadyUsed','This username is already taken!'),
('en','langEmail','e-mail'),
('en','langActiveSuccess','Your account is successfully activated!'),
('en','langActiveError','Old or invalid activation key!'),
('en','langActiveMail','To activate click on the following link:'),
('en','lang_sendMailError','Error mail send'),
('en','lang_achievsPlayers','Players who complete the achievement'),
('en','lang_achievPlayerTotal','Just completed the achievements:'),
('en','lang_achievsUnlocked','Unlocked: '),
('en','langDescription','Description'),
('en','langCount','Count'),
('en','langType','Type'),
('en','langAdd','Add'),
('en','lang_achiev_admin','Management achievements'),
('en','langMyAchiev','My achievements'),
('en','langSearch','Search'),
('en','lang_green_chat','The VIP prefix in chat'),
('en','lang_seeing_list','List watching'),
('en','lang_trail','/trail'),
('en','lang_whois','Whois'),
('en','langKzPro','Pro'),
('en','langKzNoob','Noob'),
('en','langKzAll','All'),
('en','langStats','Statistics: '),
('en','langMap','Map'),
('en','langPlayer','Player'),
('en','lang_players','Players'),
('en','langTime','Time'),
('en','langCp','Checkpoints'),
('en','langGoCp','Teleports'),
('en','langWeapon','Weapon'),
('en','langRecords','Records'),
('en','langCountry','Country'),
('en','langView','detail...'),
('en','langRecs','Record'),
('en','langWorldRecord','World record'),
('en','langRuRecord','Russian record'),
('en','langKzNum','All'),
('en','langKzTop1','First'),
('en','langKzNoRec','Not jumped'),
('en','langKzRec','Passed'),
('en','langKzStats','KZ Statistics'),
('en','langDRStats','DR Statistics'),
('en','langCity','City'),
('en','lang_achievCompleted','Fulfilled achievements: '),
('en','langMapCompleted','Went KZ maps: '),
('en','lang_kz_duels','KZ Duels'),
('en','lang_kz_maps','KZ Maps'),
('en','lang_kz_players','KZ Players'),
('en','langWinner','Winner'),
('en','langLooser','Looser'),
('en','langWinnerPoint','Winner Point'),
('en','langLooserPoint','Looser Point'),
('en','langMyKz','My KZ records'),
('en','langAuthNickPassword','Username and password'),
('en','langAuthSteamId','Steam ID'),
('en','langAuthType','The type of authorization'),
('en','langBanned','You are banned!!!'),
('en','langTitleGameAcc','Game account'),
('en','langTitleSettings','Setting'),
('en','langTitlePersonalData','Personal Data'),
('en','langICQ','ICQ'),
('en','langAvatar','Avatar'),
('en','lang_steam_login','Sign in through Steam'),
('en','langNoSteamLogin','Or fill out the form'),
('en','lang_setup','Setup config'),
('en','langSave','Save'),
('en','langSaved','Saved'),
('en','langReset','Reset'),
('en','langResetDef','Reset to default'),
('en','langConfirm','Confirmed action'),
('en','lang_timezone','Time zone'),
('en','lang_charset','Charset'),
('en','lang_mysql_user','User db'),
('en','lang_mysql_password','Password db'),
('en','lang_mysql_host','Host db'),
('en','lang_mysql_db','Database'),
('en','lang_mysql_prefix','Prefix db'),
('en','lang_activateTime','Activation time e-mail'),
('en','lang_baseUrl','Url site'),
('en','lang_gravatarSize','Avatar size'),
('en','lang_playerPerPage','Players per page'),
('en','lang_mapsPerPage','Maps per page'),
('en','lang_playersPerPage','Players per page KZ'),
('en','lang_langlist','Language list (space specarate)'),
('en','lang_lang','Language default'),
('en','lang_themelist','Theme list (space specarate)'),
('en','lang_theme','Theme default'),
('en','lang_cstheme','Theme default in CS'),
('en','lang_email','E-mail'),
('en','lang_cookieKey','Cookie Key'),
('en','langGenerate','Generate'),
('en','lang_setupGeneral','General setting'),
('en','lang_setupDb','Database'),
('en','lang_setupLang','Language'),
('en','langDbTitle','Working with database'),
('en','langBase','DB'),
('en','langTables','Tables'),
('en','langData','Data'),
('en','langCreate','Create'),
('en','langDelete','Delete'),
('en','langClear','Clear'),
('en','langEdit','Edit'),
('en','langDbNotConnect','Not connection to database'),
('en','langDbNotTablesFile','File with tables not found'),
('en','langDbNotDataFile','File with data not found'),
('en','langGlobal','Global'),
('en','langLocal','Local'),
('en','langError','Error'),
('en','lang_Var','Variable'),
('ru','lang_Var','Переменная'),
('en','lang_Value','Value'),
('ru','lang_Value','Значение'),
('en','lang_kz_player','KZ Player'),
('ru','lang_kz_player','KZ Игрок'),
('en','lang_kz_map','Kz Map'),
('ru','lang_kz_map','KZ Карта'),
('en','langTotal','Total'),
('ru','langTotal','Всего'),
('en','lang_admin_players','Edit players'),
('ru','lang_admin_players','Редактировать игроков'),
('en','lang_error','Error'),
('ru','lang_error','Ошибка'),
('en','langAdmin','Admin'),
('ru','langAdmin','Админ'),
('en','langActive','Active'),
('ru','langActive','Активный'),
('en','langYes','Yes'),
('ru','langYes','Да'),
('en','langNo','No'),
('ru','langNo','Нет'),
('en','langError401','Not autorised'),
('ru','langError401','Пользователь не авторизован'),
('en','langError403','Access denied'),
('ru','langError403','Доспуп запещен'),
('en','langError404','Pages Not Found'),
('ru','langError404','Страница не существует'),
('en','langError500','Internal Server Error'),
('ru','langError500','Внутренняя ошибка сервера'),
('en','langDownload','Download'),
('ru','langDownload','Скачать');