DELETE FROM `unr_players` ;
INSERT INTO `unr_players` (`id`, `name`, `password`, `email`, `active`, `webadmin`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'admin@site.com', 1, 1),
(2, 'test1', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0),
(3, 'test2', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0),
(4, 'test3', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0),
(5, 'test4', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0),
(6, 'test5', '21232f297a57a5a743894a0e4a801fc3', 'test@mail.com', 1, 0);

DELETE FROM `servers`;
INSERT  INTO `servers`(`id`,`name`,`addres`) VALUES
(1,'[K.lan] CSDM','cs.klan-hub.ru:27015'),
(2,'[K.lan] Classic','cs.klan-hub.ru:27016'),
(3,'[K.lan] Kreedz','cs.klan-hub.ru:27017'),
(4,'[K.lan] Zombie Plague','cs.klan-hub.ru:27018');

DELETE FROM `servers_lang`;
INSERT  INTO `servers_lang`(`id`,`serverid`,`lang`,`desc`) VALUES 
(1,1,'ru','Любите безостановочную стрельбу'),
(2,2,'ru','Вы сторонник классической игры'),
(3,3,'ru','Нравится паркур'),
(4,4,'ru','Окутайтесь в атмосферу страха и ужаса'),
(5,1,'en','Like non-stop shooting'),
(6,2,'en','You are a supporter of the classic game'),
(7,3,'en','Like the parkour'),
(8,4,'en','Acetates in an atmosphere of fear and terror');

DELETE FROM `unr_achiev`;
insert  into `unr_achiev`(`id`,`type`,`count`) values 
(1,'money_t',125000),
(2,'dominate_o',1),
(3,'kill_l',1),
(4,'dominate_m',1),
(5,'kill_s',1),
(6,'dominate_n',1),
(7,'dominate_d',4),
(8,'dominate_o',10),
(9,'dominate_t',3),
(10,'kill_d',1),
(11,'kill_e',500),
(12,'airkill_u',1),
(13,'money_t',2500000),
(14,'spray',100),
(15,'dominate_m',20),
(16,'airkill_b',1),
(17,'kill_e',10000),
(18,'airkill_e',1),
(19,'flash_t',5),
(20,'money_t',50000000),
(21,'say',1000),
(22,'spray',1000),
(23,'money_b',100000),
(24,'headshoots_in_round',5),
(25,'95dmg',1),
(26,'5dmg',1),
(27,'break_in_round',10),
(28,'win_round',10),
(29,'win_round',200),
(30,'win_round',5000),
(31,'1sek_defusing',1),
(32,'bomb_plant',100),
(33,'bomb_defuse',100),
(34,'de_dust2_win_round',100),
(35,'break',500),
(36,'de_nuke_win_round',100),
(37,'deathrun_temple_win_round',100),
(38,'surf_ski_2_win_round',100),
(39,'awp_rooftops_win_round',100),
(40,'hns_floppytown_win_round',100),
(41,'money_t',1000000),
(42,'collect_halloween_present',20);

DELETE FROM `unr_achiev_lang`;
insert  into `unr_achiev_lang`(`lang`,`var`,`value`) values
('ru','WarBond','Военные Облигации'),
('ru','RepeatOffender','Рецидивист'),
('ru','MagicBullet','Волшебная Пуля'),
('ru','PositionStrength','С позиции силы'),
('ru','EyeEye','Глаза в глаза'),
('ru','Insurgent','Боевик'),
('ru','ExcessiveBrutality','Чрезмерная Жестокость'),
('ru','Decimator','Дециматор'),
('ru','HetTrick','Хет-трик'),
('ru','SavingAmm','Экономия патронов'),
('ru','Corpsman','Санитар'),
('ru','DeathSky','Смерть с неба'),
('ru','SpoilsWar','Трофеи войны'),
('ru','ArtWar','Искусство войны'),
('ru','DontTouch','Не тронь меня!'),
('ru','AerialNecrobatics','Воздушный Necrobatics'),
('ru','GodWar','Бог войны'),
('ru','BunnyHunt','Банни Хант'),
('ru','HelloGuys','Привет, Ребята'),
('ru','BloodMoney','Кровавые Деньги'),
('ru','TalkativePlayer','Общительный игрок'),
('ru','DayYouth','День молодежи'),
('ru','RichPlayer','Богатый игрок'),
('ru','HeadShred','Глава Лоскуток Выкупа'),
('ru','Primer','Праймер'),
('ru','FinishingSchooled','Отделка Вышколены'),
('ru','MadProps','Баальшой Респект'),
('ru','NewbWorld','Ньют Мировой Порядок'),
('ru','ProMoted','Поощрятель'),
('ru','LeetMen','Leet мужчина'),
('ru','SecondNone','Второй нет'),
('ru','Boomala','Boomala Boomala'),
('ru','HurtBlocker','Блокиратор Больно'),
('ru','Veteran','Ветеран карты Dust2'),
('ru','Destroyer','Разрушитель'),
('ru','VeteranNuke','Ветеран карты Nuke'),
('ru','VeteranTemple','Ветеран карты Temple'),
('ru','VeteranSki2','Ветеран карты ski 2'),
('ru','VeteranRooftops','Ветеран карты rooftops'),
('ru','VeteranFloppytown','Ветеран карты floppytown'),
('ru','VeteranOIL','НЕФТЬ! Я БОГАТ!'),
('ru','Halloween','Хэллоуин время!'),
('ru','DescWarBond','Заработать $125,000'),
('ru','DescRepeatOffender','Доминировать над вражеским игроком'),
('ru','DescMagicBullet','Убить врага последним патроном в магазине'),
('ru','DescPositionStrength','Убить противника, над которым вы уже доминируете'),
('ru','DescEyeEye','Убить из снайперской винтовки вражеского снайпера'),
('ru','DescInsurgent','Убить вражеского игрока, который над вами доминирует'),
('ru','DescExcessiveBrutality','Убить вражеского игрока еще 4 раза, когда вы уже доминируете над ним'),
('ru','DescDecimator','Доминировать над 10 вражескими игроками'),
('ru','DescHetTrick','Доминировать одновременно над тремя вражескими игроками'),
('ru','DescSavingAmm','Убить двух противников одной пулей'),
('ru','DescCorpseman','Убить 500 врагов'),
('ru','DescDeathSky','Убить врага, находясь в воздухе'),
('ru','DescSpoilsWar','Заработать $2,500,000'),
('ru','DescArtWar','Нарисовать 100 рисунков'),
('ru','DescDontTouch','Убить 20 вражеских игроков, которые доминируют над вами'),
('ru','DescAerialNecrobatics','Находясь в воздухе, убить врага, тоже находящегося в воздухе'),
('ru','DescGodWar','Убить 10000 врагов'),
('ru','DescBunnyHunt','Убить врага, находящегося в воздухе'),
('ru','DescHelloGuys','Ослепить товарищей 5 раз'),
('ru','DescBloodMoney','Заработать $50,000,000'),
('ru','DescTalkativePlayer','Написать в чат 1000 сообщений'),
('ru','DescDayYouth','Нарисовать 1000 рисунков'),
('ru','DescRichPlayer','Потратить $100,000'),
('ru','DescHeadShred','Убить 5 врагов выстрелами в голову за один раунд'),
('ru','DescPrimer','Нанести 95% урона врагу, которого затем убивает другой игрок'),
('ru','DescFinishingSchooled','Убить врага, который доведен до уровня мнее 5% здоровья другим игроком'),
('ru','DescMadProps','Сломать 10 предметов за один раунд'),
('ru','DescNewbWorld','Выиграть 10 раундов'),
('ru','DescProMoted','Выиграть 200 раундов'),
('ru','DescLeetMen','Выиграть 5000 раундов'),
('ru','DescSecondNone','Успешно обезвредить бомбу менее чем за одну секунду до взрыва'),
('ru','DescBoomala','Установить 100 бомб'),
('ru','DescHurtBlocker','Обезвредить 100 бомб'),
('ru','DescVeteran','Выиграть 100 раундов на карте de_dust2'),
('ru','DescDestroyer','Сломать 500 предметов'),
('ru','DescVeteranNuke','Выиграть 100 раундов на карте de_nuke'),
('ru','DescVeteranTemple','Выиграть 100 раундов на карте deathrun_temple'),
('ru','DescVeteranSki2','Выиграть 100 раундов на карте surf_ski_2'),
('ru','DescVeteranRooftops','Выиграть 100 раундов на карте awp_rooftops'),
('ru','DescVeteranFloppytown','Выиграть 100 раундов на карте hns_floppytown'),
('ru','DescVeteranOIL','Заработать $1,000,000'),
('ru','DescHalloween','Собрать 20 мешков с подарками в период с 29.10 по 3.11'),
('en','WarBond','War Bonds'),
('en','RepeatOffender','Repeat Offender'),
('en','MagicBullet','Magic Bullet'),
('en','PositionStrength','From a position of strength'),
('en','EyeEye','Eye to Eye'),
('en','Insurgent','Insurgent'),
('en','ExcessiveBrutality','Excessive Brutality'),
('en','Decimator','Decimator'),
('en','HetTrick','A hat-trick'),
('en','SavingAmm','Saving ammunition'),
('en','Corpsman','Corpsman'),
('en','DeathSky','Смерть с неба'),
('en','SpoilsWar','Spoils of War'),
('en','ArtWar','The Art of War'),
('en','DontTouch','Don\'t touch me!'),
('en','AerialNecrobatics','Aerial Necrobatics'),
('en','GodWar','God of War'),
('en','BunnyHunt','Bunny Hunt'),
('en','HelloGuys','Hello Guys'),
('en','BloodMoney','Blood Money'),
('en','TalkativePlayer','A talkative player'),
('en','DayYouth','Youth day'),
('en','RichPlayer','Rich player'),
('en','HeadShred','Head Shred Redemption'),
('en','Primer','Primer'),
('en','FinishingSchooled','Finishing Schooled'),
('en','MadProps','Mad Props'),
('en','NewbWorld','Newb World Order'),
('en','ProMoted','Pro-moted'),
('en','LeetMen','Leet-er of Men'),
('en','SecondNone','Second to None'),
('en','Boomala','Boomala Boomala'),
('en','HurtBlocker','The Hurt Blocker'),
('en','Veteran','Veteran maps Dust2'),
('en','Destroyer','Разрушитель'),
('en','VeteranNuke','Veteran maps Nuke'),
('en','VeteranTemple','Veteran maps Temple'),
('en','VeteranSki2','Veteran maps ski 2'),
('en','VeteranRooftops','Veteran maps rooftops'),
('en','VeteranFloppytown','Veteran maps floppytown'),
('en','VeteranOIL','OIL! I\'M RICH!'),
('en','Halloween','Halloween time!'),
('en','DescWarBond','Earn $125,000'),
('en','DescRepeatOffender','Dominate an enemy player'),
('en','DescMagicBullet','Kill an enemy with the last bullet in the store'),
('en','DescPositionStrength','Kill the enemy, over which you already dominate'),
('en','DescEyeEye','To kill from a sniper rifle the enemy sniper'),
('en','DescInsurgent','Kill an enemy player that is dominating over you'),
('en','DescExcessiveBrutality','Kill an enemy player 4 times when you already dominate it'),
('en','DescDecimator','To dominate the 10 enemy players'),
('en','DescHetTrick','At the same time to dominate three enemy players'),
('en','DescSavingAmm','Kill two enemies with one bullet'),
('en','DescCorpseman','Kill 500 enemies'),
('en','DescDeathSky','Kill an enemy while in the air'),
('en','DescSpoilsWar','Earn $2,500,000'),
('en','DescArtWar','To draw 100 drawings'),
('en','DescDontTouch','Kill 20 enemy players that are dominating you'),
('en','DescAerialNecrobatics','While in the air, to kill the enemy is also in the air'),
('en','DescGodWar','Kill 10,000 enemies'),
('en','DescBunnyHunt','Kill the enemy in the air'),
('en','DescHelloGuys','Dazzle comrades 5 times'),
('en','DescBloodMoney','Earn $50,000,000'),
('en','DescTalkativePlayer','Write in the chat 1000 messages'),
('en','DescDayYouth','To draw 1,000 drawings'),
('en','DescRichPlayer','To spend $100,000'),
('en','DescHeadShred','Kill 5 enemies with headshots in a single round'),
('en','DescPrimer','To inflict 95% damage to enemy that then kills the other player'),
('en','DescFinishingSchooled','Kill the enemy that brought to the level of less than 5% health by other player'),
('en','DescMadProps','Break 10 objects in a single round'),
('en','DescNewbWorld','Win 10 rounds'),
('en','DescProMoted','Win 200 rounds'),
('en','DescLeetMen','Win 5,000 rounds'),
('en','DescSecondNone','Successfully defuse a bomb in less than one second before the explosion'),
('en','DescBoomala','Install 100 bombs'),
('en','DescHurtBlocker','Defuse 100 bombs'),
('en','DescVeteran','Win 100 rounds on the de_dust2 map'),
('en','DescDestroyer','Break 500 objects'),
('en','DescVeteranNuke','Win 100 rounds on the de_nuke map'),
('en','DescVeteranTemple','Win 100 rounds on the map deathrun_temple'),
('en','DescVeteranSki2','Win 100 rounds on the map surf_ski_2'),
('en','DescVeteranRooftops','Win 100 rounds on the map awp_rooftops'),
('en','DescVeteranFloppytown','Win 100 rounds on the map hns_floppytown'),
('en','DescVeteranOIL','To earn $1,000,000'),
('en','DescHalloween','Collect 20 bags of gifts in the period from 29.10 till 3.11');

DELETE FROM `weapons`;
insert  into `weapons`(`id`,`name`,`fullname`) values 
(0,'NONE',''),
(1,'P228','SIG Sauer P228'),
(2,'WAT',''),
(3,'SCOUT','Steyr Scout'),
(4,'HEGRENADE','He Grenade'),
(5,'XM1014','Benelli M4 Super 90'),
(6,'C4','C4'),
(7,'MAC10','Ingram MAC-10'),
(8,'AUG','Steyr AUG'),
(9,'SMOKEGRENADE','Smoke Grenade'),
(10,'ELITE','Elite'),
(11,'FIVESEVEN','FN Five-seveN'),
(12,'UMP45','HK UMP'),
(13,'SG550','SIG SG 550'),
(14,'GALIL','Galil'),
(15,'FAMAS','Famas'),
(16,'USP','HK USP'),
(17,'GLOCK18','Glock 18'),
(18,'AWP','Accuracy International L96A1'),
(19,'MP5NAVY','HK MP5'),
(20,'M249','M249 SAW'),
(21,'M3','M3 submachine gun'),
(22,'M4A1','M4 carbine'),
(23,'TMP','Steyr TMP'),
(24,'G3SG1','HK G3'),
(25,'FLASHBANG','Flash Bang'),
(26,'DEAGLE','Desert Eagle'),
(27,'SG552','SIG SG 550'),
(28,'AK47','AK47'),
(29,'KNIFE','Knife'),
(30,'P90','FN P90'),
(31,'VEST','Vest'),
(32,'VESTHELM','Vest Helm');

DELETE FROM `lang`;
insert  into `lang`(`lang`,`var`,`value`) values
('ru','langLang_ru','Русский'),
('ru','langLang_en','English'),
('ru','langTheme_main','Стандарная'),
('ru','langTheme_white','Инвертная'),
('ru','langTheme_image','Картинки'),
('ru','langTheme_null','Пустая'),
('ru','langThemeNotFound','тема не существует'),
('ru','langMain','Главная'),
('ru','lang_home','Начало'),
('ru','lang_achiev','Достижения'),
('ru','lang_ucp','Личный кабинет'),
('ru','lang_logout','Выйти'),
('ru','langTitle','Lonis'),
('ru','lang_admin_achiev','Настройка достижений'),
('ru','lang_admin_lang','Язык'),
('ru','langRegErrors','Произошли следующие ошибки:'),
('ru','langNotInputNick','Вы не ввели ник!'),
('ru','langNotInputPassword','Вы не ввели пароль!'),
('ru','langNotInputMail','Вы не ввели e-mail!'),
('ru','langAlreadyLogin','Вы уже вошли!'),
('ru','langWarning','Внимание!'),
('ru','langUserNotFound','Не найден пользователь с введёнными вами данными!'),
('ru','langName','Имя'),
('ru','langPassword','Пароль'),
('ru','lang_login','Войти'),
('ru','lang_loginReg','Войти/Регистрация'),
('ru','lang_reg','Регистрация'),
('ru','lang_regTitle','Регистрация'),
('ru','langMustLogin','Необходимо войти!'),
('ru','langDataUpdated','Данные успешно обновлены!'),
('ru','langIP','IP'),
('ru','langSteamID','Steam ID'),
('ru','langUpdate','Обновить'),
('ru','langReadme','Бла бла бла'),
('ru','langCurrent','Текущий'),
('ru','langInActive','Учётная запись неактивна!'),
('ru','langAlreadyRegister','Вы уже зарегистрированы!'),
('ru','lang_regSuccess','Вы успешно зарегистрированы! Ссылка для активации отправлена на указанный e-mail'),
('ru','langAlreadyUsed','Такое имя пользователя уже занято!'),
('ru','langEmail','e-mail'),
('ru','langActiveSuccess','Ваша учётная запись успешно активирована!'),
('ru','langActiveError','Неверный либо старый ключ активации!'),
('ru','langActiveMail','Для активации пройдите по следующей ссылке:'),
('ru','lang_sendMailError','Ошибка отправки почты'),
('ru','lang_achievsPlayers','Игроки, выполнившие достижение'),
('ru','lang_achievPlayerTotal','Всего выполнено достижений:'),
('ru','lang_achievsUnlocked','Разблокировано: '),
('ru','langDescription','Описание'),
('ru','langCount','Количество'),
('ru','langType','Тип'),
('ru','langAdd','Добавить'),
('ru','lang_achiev_admin','Управление достижениями'),
('ru','lang_achiev_players','Достижения игроков'),
('ru','langMyAchiev','Мои достижения'),
('ru','langSearch','Поиск'),
('ru','lang_green_chat','Префикс VIP в чате'),
('ru','lang_seeing_list','Список наблюдающих'),
('ru','lang_trail','/trail'),
('ru','lang_whois','Whois'),
('ru','langKzPro','Про'),
('ru','langKzNoob','Новички'),
('ru','langKzAll','Все'),
('ru','langStats','Статистика: '),
('ru','langMap','Карта '),
('ru','langPlayer','Игрок'),
('ru','lang_players','Игроки'),
('ru','langTime','Время'),
('ru','langCp','Чекпоинтов'),
('ru','langGoCp','Телепортов'),
('ru','langWeapon','Оружие'),
('ru','langRecords','Рекордов'),
('ru','langCountry','Страна'),
('ru','langView','подробно...'),
('ru','langRecs','Рекорд'),
('ru','langWorldRecord','Мировой рекорд'),
('ru','langRuRecord','Русский рекорд'),
('ru','langKzNum','Всего'),
('ru','langKzTop1','Первый'),
('ru','langKzNoRec','Не пройденные'),
('ru','langKzRec','Пройденные'),
('ru','langKzStats','KZ Статистика'),
('ru','langDRStats','DR Статистика'),
('ru','langCity','Город'),
('ru','lang_achievCompleted','Выполнил достижений: '),
('ru','langMapCompleted','Прошёл KZ карт: '),
('ru','lang_kz_duels','KZ Дуэль'),
('ru','lang_kz_maps','KZ карты'),
('ru','lang_kz_players','KZ игроки'),
('ru','langWinner','Победитель'),
('ru','langLooser','Проигравший'),
('ru','langWinnerPoint','Очков победителя'),
('ru','langLooserPoint','Очков проигравшего'),
('ru','langMyKz','Мои KZ рекорды'),
('ru','langAuthNickPassword','Ник и пароль'),
('ru','langAuthSteamId','Steam ID'),
('ru','langAuthType','Тип авторизации'),
('ru','langBanned','Вы забанены!!!'),
('ru','langTitleGameAcc','Игровой аккаунт'),
('ru','langTitleSettings','Настройки'),
('ru','langTitlePersonalData','Личные данные'),
('ru','langICQ','ICQ'),
('ru','langAvatar','Аватар'),
('ru','lang_steam_login','Войдите через Steam'),
('ru','langNoSteamLogin','Или заполните форму'),
('ru','lang_setup','Настройка конфига'),
('ru','langSave','Сохранить'),
('ru','langSaved','Сохранено'),
('ru','langReset','Сбросить'),
('ru','langResetDef','Сбросить настройки'),
('ru','langConfirm','Подтвердите действие'),
('ru','lang_timezone','Временная зона'),
('ru','lang_charset','Кодировка'),
('ru','lang_mysql_user','Пользователь базы'),
('ru','lang_mysql_password','Пароль базы'),
('ru','lang_mysql_host','Адрес базы'),
('ru','lang_mysql_db','База'),
('ru','lang_mysql_prefix','Префикс'),
('ru','lang_activateTime','Время активации профиля'),
('ru','lang_baseUrl','Адрес сайта'),
('ru','lang_gravatarSize','Размер аватара'),
('ru','lang_playerPerPage','Игроков на странице'),
('ru','lang_mapsPerPage','Карт на странице'),
('ru','lang_playersPerPage','Игроков на странице KZ'),
('ru','lang_langlist','Список языков (через пробел)'),
('ru','lang_lang','Язык по умолчанию'),
('ru','lang_themelist','Список тем (через пробел)'),
('ru','lang_theme','Тема по умолчанию'),
('ru','lang_cstheme','Тема по умолчанию в CS'),
('ru','lang_email','E-mail'),
('ru','lang_cookieKey','Cookie Ключ'),
('ru','langGenerate','Генерировать'),
('ru','lang_setupGeneral','Основные настройки'),
('ru','lang_setupDb','База данных'),
('ru','lang_setupLang','Язык'),
('ru','langDbTitle','Работа с базой данных'),
('ru','langBase','База'),
('ru','langTables','Таблицы'),
('ru','langData','Данные'),
('ru','langCreate','Создать'),
('ru','langDelete','Удалить'),
('ru','langClear','Очистить'),
('ru','langEdit','Изменить'),
('ru','langDbNotConnect','Нет подключения к базе данных'),
('ru','langDbNotTablesFile','Файл с таблицами не существует'),
('ru','langDbNotDataFile','Файл с данными не существует'),
('ru','langGlobal','Глобальные'),
('ru','langLocal','Локальные'),
('ru','langError','Ошибка'),
('en','langLang_ru','Русский'),
('en','langLang_en','English'),
('en','langTheme_main','Standart'),
('en','langTheme_white','Invert'),
('en','langTheme_image','Images'),
('en','langTheme_null','Empty'),
('en','langThemeNotFound','Theme not found'),
('en','langMain','Main'),
('en','lang_home','Home'),
('en','lang_achiev','Achievs'),
('en','lang_ucp','Personal account'),
('en','lang_logout','Logout'),
('en','langTitle','Lonis'),
('en','lang_admin_achiev','Setup achiev'),
('en','lang_admin_lang','Dictonaries'),
('en','langRegErrors','Failed with the following error:'),
('en','langNotInputNick','You did not enter nick!'),
('en','langNotInputPassword','You have not entered a password!'),
('en','langNotInputMail','You have not entered e-mail!'),
('en','langAlreadyLogin','You already entered!'),
('en','langWarning','Warning!'),
('en','langUserNotFound','Not found user entered data!'),
('en','langName','Name'),
('en','langPassword','Password'),
('en','lang_login','Login'),
('en','lang_loginReg','Login/Register'),
('en','lang_reg','Register'),
('en','lang_regTitle','Registration'),
('en','lang_achiev_players','Achievs players'),
('en','langMustLogin','You need to login!'),
('en','langDataUpdated','Data updated successfully!'),
('en','langIP','IP'),
('en','langSteamID','Steam ID'),
('en','langUpdate','Update'),
('en','langReadme','Bla Bla Bla'),
('en','langCurrent','Current'),
('en','langInActive','Account inactive!'),
('en','langAlreadyRegister','You are already registered!'),
('en','lang_regSuccess','You have successfully registered! Activation link sent to your e-mail'),
('en','langAlreadyUsed','This username is already taken!'),
('en','langEmail','e-mail'),
('en','langActiveSuccess','Your account is successfully activated!'),
('en','langActiveError','Old or invalid activation key!'),
('en','langActiveMail','To activate click on the following link:'),
('en','lang_sendMailError','Error mail send'),
('en','lang_achievsPlayers','Players who complete the achievement'),
('en','lang_achievPlayerTotal','Just completed the achievements:'),
('en','lang_achievsUnlocked','Unlocked: '),
('en','langDescription','Description'),
('en','langCount','Count'),
('en','langType','Type'),
('en','langAdd','Add'),
('en','lang_achiev_admin','Management achievements'),
('en','langMyAchiev','My achievements'),
('en','langSearch','Search'),
('en','lang_green_chat','The VIP prefix in chat'),
('en','lang_seeing_list','List watching'),
('en','lang_trail','/trail'),
('en','lang_whois','Whois'),
('en','langKzPro','Pro'),
('en','langKzNoob','Noob'),
('en','langKzAll','All'),
('en','langStats','Statistics: '),
('en','langMap','Map'),
('en','langPlayer','Player'),
('en','lang_players','Players'),
('en','langTime','Time'),
('en','langCp','Checkpoints'),
('en','langGoCp','Teleports'),
('en','langWeapon','Weapon'),
('en','langRecords','Records'),
('en','langCountry','Country'),
('en','langView','detail...'),
('en','langRecs','Record'),
('en','langWorldRecord','World record'),
('en','langRuRecord','Russian record'),
('en','langKzNum','All'),
('en','langKzTop1','First'),
('en','langKzNoRec','Not jumped'),
('en','langKzRec','Passed'),
('en','langKzStats','KZ Statistics'),
('en','langDRStats','DR Statistics'),
('en','langCity','City'),
('en','lang_achievCompleted','Fulfilled achievements: '),
('en','langMapCompleted','Went KZ maps: '),
('en','lang_kz_duels','KZ Duels'),
('en','lang_kz_maps','KZ Maps'),
('en','lang_kz_players','KZ Players'),
('en','langWinner','Winner'),
('en','langLooser','Looser'),
('en','langWinnerPoint','Winner Point'),
('en','langLooserPoint','Looser Point'),
('en','langMyKz','My KZ records'),
('en','langAuthNickPassword','Username and password'),
('en','langAuthSteamId','Steam ID'),
('en','langAuthType','The type of authorization'),
('en','langBanned','You are banned!!!'),
('en','langTitleGameAcc','Game account'),
('en','langTitleSettings','Setting'),
('en','langTitlePersonalData','Personal Data'),
('en','langICQ','ICQ'),
('en','langAvatar','Avatar'),
('en','lang_steam_login','Sign in through Steam'),
('en','langNoSteamLogin','Or fill out the form'),
('en','lang_setup','Setup config'),
('en','langSave','Save'),
('en','langSaved','Saved'),
('en','langReset','Reset'),
('en','langResetDef','Reset to default'),
('en','langConfirm','Confirmed action'),
('en','lang_timezone','Time zone'),
('en','lang_charset','Charset'),
('en','lang_mysql_user','User db'),
('en','lang_mysql_password','Password db'),
('en','lang_mysql_host','Host db'),
('en','lang_mysql_db','Database'),
('en','lang_mysql_prefix','Prefix db'),
('en','lang_activateTime','Activation time e-mail'),
('en','lang_baseUrl','Url site'),
('en','lang_gravatarSize','Avatar size'),
('en','lang_playerPerPage','Players per page'),
('en','lang_mapsPerPage','Maps per page'),
('en','lang_playersPerPage','Players per page KZ'),
('en','lang_langlist','Language list (space specarate)'),
('en','lang_lang','Language default'),
('en','lang_themelist','Theme list (space specarate)'),
('en','lang_theme','Theme default'),
('en','lang_cstheme','Theme default in CS'),
('en','lang_email','E-mail'),
('en','lang_cookieKey','Cookie Key'),
('en','langGenerate','Generate'),
('en','lang_setupGeneral','General setting'),
('en','lang_setupDb','Database'),
('en','lang_setupLang','Language'),
('en','langDbTitle','Working with database'),
('en','langBase','DB'),
('en','langTables','Tables'),
('en','langData','Data'),
('en','langCreate','Create'),
('en','langDelete','Delete'),
('en','langClear','Clear'),
('en','langEdit','Edit'),
('en','langDbNotConnect','Not connection to database'),
('en','langDbNotTablesFile','File with tables not found'),
('en','langDbNotDataFile','File with data not found'),
('en','langGlobal','Global'),
('en','langLocal','Local'),
('en','langError','Error'),
('en','lang_Var','Variable'),
('ru','lang_Var','Переменная'),
('en','lang_Value','Value'),
('ru','lang_Value','Значение'),
('en','lang_kz_player','KZ Player'),
('ru','lang_kz_player','KZ Игрок'),
('en','lang_kz_map','Kz Map'),
('ru','lang_kz_map','KZ Карта'),
('en','langTotal','Total'),
('ru','langTotal','Всего'),
('en','lang_admin_players','Edit players'),
('ru','lang_admin_players','Редактировать игроков'),
('en','lang_error','Error'),
('ru','lang_error','Ошибка'),
('en','langAdmin','Admin'),
('ru','langAdmin','Админ'),
('en','langActive','Active'),
('ru','langActive','Активный'),
('en','langYes','Yes'),
('ru','langYes','Да'),
('en','langNo','No'),
('ru','langNo','Нет'),
('en','langError401','Not autorised'),
('ru','langError401','Пользователь не авторизован'),
('en','langError403','Access denied'),
('ru','langError403','Доспуп запещен'),
('en','langError404','Pages Not Found'),
('ru','langError404','Страница не существует'),
('en','langError500','Internal Server Error'),
('ru','langError500','Внутренняя ошибка сервера'),
('en','langDownload','Download'),
('ru','langDownload','Скачать'),
('en','lang_servers','Servers'),
('ru','lang_servers','Сервера'),
('en','langWelcome','Welcome to game server'),
('ru','langWelcome','Добро пожаловать на игровые сервера'),
('en','lang_achievPerPage','Lines in Achiev'),
('ru','lang_achievPerPage','Строк в Достижениях'),
('en','langBots','Bots'),
('ru','langBots','Боты'),
('en','langOS','OS'),
('ru','langOS','ОС'),
('en','langDescriptor','Descriptor'),
('ru','langDescriptor','Дескриптор'),
('en','langMod','Mod'),
('ru','langMod','Мод'),
('en','langFrags','Frags'),
('ru','langFrags','Очки'),
('en','langServerNotFound','Server not found'),
('ru','langServerNotFound','Сервер не найден'),
('en','langCheck','Check'),
('ru','langCheck','Проверить'),
('en','langLanguage','Language'),
('ru','langLanguage','Язык'),
('en','lang_admin_servers','Edit servers'),
('ru','lang_admin_servers','Изменить сервера');