/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `langs`;
CREATE TABLE IF NOT EXISTS `langs` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `lang` varchar(2) NOT NULL,
  `var` varchar(256) NOT NULL,
  `value` varchar(256) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `langs` DISABLE KEYS */;
INSERT INTO `langs` (`id`, `lang`, `var`, `value`) VALUES
	(1, 'ru', 'Theme not found', 'тема не существует'),
	(2, 'ru', 'Main', 'Главная'),
	(3, 'ru', 'Home', 'Начало'),
	(4, 'ru', 'Achievs', 'Достижения'),
	(5, 'ru', 'Account', 'Аккаунт'),
	(6, 'ru', 'Logout', 'Выйти'),
	(7, 'ru', 'Lonis', 'Lonis'),
	(8, 'ru', 'Setup achiev', 'Настройка достижений'),
	(9, 'ru', 'Langs', 'Словарь'),
	(10, 'ru', 'Failed with the following error:', 'Произошли следующие ошибки:'),
	(11, 'ru', 'You did not enter nick!', 'Вы не ввели ник!'),
	(12, 'ru', 'You have not entered a password!', 'Вы не ввели пароль!'),
	(13, 'ru', 'You have not entered e-mail!', 'Вы не ввели e-mail!'),
	(14, 'ru', 'You already entered!', 'Вы уже вошли!'),
	(15, 'ru', 'Warning!', 'Внимание!'),
	(16, 'ru', 'Player not found', 'Игрок не найден'),
	(17, 'ru', 'Name', 'Имя'),
	(18, 'ru', 'Password', 'Пароль'),
	(19, 'ru', 'Login', 'Войти'),
	(20, 'ru', 'Login/Register', 'Войти / Регистрация'),
	(21, 'ru', 'Register', 'Регистрация'),
	(22, 'ru', 'Registration', 'Регистрация'),
	(23, 'ru', 'You need to login!', 'Необходимо войти!'),
	(24, 'ru', 'Data updated successfully!', 'Данные успешно обновлены!'),
	(25, 'ru', 'IP', 'IP'),
	(26, 'ru', 'Steam ID', 'Steam ID'),
	(27, 'ru', 'Update', 'Обновить'),
	(28, 'ru', 'Bla Bla Bla', 'Бла бла бла'),
	(29, 'ru', 'Current', 'Текущий'),
	(30, 'ru', 'Account inactive!', 'Учётная запись неактивна!'),
	(31, 'ru', 'You are already registered!', 'Вы уже зарегистрированы!'),
	(32, 'ru', 'You have successfully registered!', 'Вы успешно зарегистрированы!'),
	(33, 'ru', 'This player is already exists!', 'Такой игрок существует!'),
	(34, 'ru', 'e-mail', 'e-mail'),
	(35, 'ru', 'Account is successfully activated!', 'Учётная запись успешно активирована!'),
	(36, 'ru', 'Old or invalid activation key!', 'Неверный либо старый ключ активации!'),
	(37, 'ru', 'To activate click on the following link:', 'Для активации пройдите по следующей ссылке:'),
	(38, 'ru', 'Error mail send', 'Ошибка отправки почты'),
	(39, 'ru', 'Players who complete the achievement', 'Игроки, выполнившие достижение'),
	(40, 'ru', 'Just completed the achievements:', 'Всего выполнено достижений:'),
	(41, 'ru', 'Unlocked', 'Разблокировано'),
	(42, 'ru', 'Description', 'Описание'),
	(43, 'ru', 'Count', 'Количество'),
	(44, 'ru', 'Type', 'Тип'),
	(45, 'ru', 'Add', 'Добавить'),
	(46, 'ru', 'Management achievements', 'Управление достижениями'),
	(47, 'ru', 'Achievs players', 'Достижения игроков'),
	(48, 'ru', 'My achievements', 'Мои достижения'),
	(49, 'ru', 'Search', 'Поиск'),
	(50, 'ru', 'The VIP prefix in chat', 'Префикс VIP в чате'),
	(51, 'ru', 'List watching', 'Список наблюдающих'),
	(52, 'ru', '/trail', '/trail'),
	(53, 'ru', 'Whois', 'Whois'),
	(54, 'ru', 'Pro', 'Про'),
	(55, 'ru', 'Noob', 'Новички'),
	(56, 'ru', 'All', 'Все'),
	(57, 'ru', 'Statistics', 'Статистика'),
	(58, 'ru', 'Map', 'Карта '),
	(59, 'ru', 'Player', 'Игрок'),
	(60, 'ru', 'Players', 'Игроки'),
	(61, 'ru', 'Time', 'Время'),
	(62, 'ru', 'Checkpoints', 'Чекпоинтов'),
	(63, 'ru', 'Teleports', 'Телепортов'),
	(64, 'ru', 'Weapon', 'Оружие'),
	(65, 'ru', 'All Records', 'Рекордов'),
	(66, 'ru', 'Country', 'Страна'),
	(67, 'ru', 'detail...', 'подробно...'),
	(68, 'ru', 'Record', 'Рекорд'),
	(69, 'ru', 'World record', 'Мировой рекорд'),
	(70, 'ru', 'Russian record', 'Русский рекорд'),
	(72, 'ru', 'First', 'Первый'),
	(73, 'ru', 'Not jumped', 'Не пройденные'),
	(74, 'ru', 'Passed', 'Пройденные'),
	(75, 'ru', 'KZ Statistics', 'KZ Статистика'),
	(76, 'ru', 'DR Statistics', 'DR Статистика'),
	(77, 'ru', 'City', 'Город'),
	(78, 'ru', 'Fulfilled achievements', 'Выполнил достижений'),
	(79, 'ru', 'Went KZ maps', 'Прошёл KZ карт'),
	(80, 'ru', 'Duels', 'Дуэль'),
	(81, 'ru', 'Maps', 'Карты'),
	(82, 'ru', 'Best', 'Лучшие'),
	(83, 'ru', 'Winner', 'Победитель'),
	(84, 'ru', 'Looser', 'Проигравший'),
	(85, 'ru', 'Winner Point', 'Очков победителя'),
	(86, 'ru', 'Looser Point', 'Очков проигравшего'),
	(87, 'ru', 'My KZ records', 'Мои KZ рекорды'),
	(88, 'ru', 'Username and password', 'Ник и пароль'),
	(90, 'ru', 'The type of authorization', 'Тип авторизации'),
	(91, 'ru', 'You are banned!!!', 'Вы забанены!!!'),
	(92, 'ru', 'Game account', 'Игровой аккаунт'),
	(93, 'ru', 'Setting', 'Настройки'),
	(94, 'ru', 'Personal Data', 'Личные данные'),
	(95, 'ru', 'ICQ', 'ICQ'),
	(96, 'ru', 'Avatar', 'Аватар'),
	(98, 'ru', 'Or fill out the form', 'Или заполните форму'),
	(99, 'ru', 'Setup config', 'Настройка конфига'),
	(100, 'ru', 'Save', 'Сохранить'),
	(101, 'ru', 'Saved', 'Сохранено'),
	(102, 'ru', 'Reset', 'Сбросить'),
	(103, 'ru', 'Reset to default', 'Сбросить по-умолчанию'),
	(104, 'ru', 'Confirmed action', 'Подтвердите действие'),
	(105, 'ru', 'Time zone', 'Временная зона'),
	(106, 'ru', 'Charset', 'Кодировка'),
	(107, 'ru', 'User db', 'Пользователь базы'),
	(108, 'ru', 'Password db', 'Пароль базы'),
	(109, 'ru', 'Host db', 'Адрес базы'),
	(111, 'ru', 'Prefix db', 'Префикс'),
	(112, 'ru', 'Activation time e-mail', 'Время активации профиля'),
	(113, 'ru', 'Url site', 'Адрес сайта'),
	(114, 'ru', 'Avatar size', 'Размер аватара'),
	(115, 'ru', 'Players per page', 'Игроков на странице'),
	(116, 'ru', 'Maps per page', 'Карт на странице'),
	(117, 'ru', 'Players per page KZ', 'Игроков на странице KZ'),
	(118, 'ru', 'Language list (space specarate)', 'Список языков (через пробел)'),
	(119, 'ru', 'Language default', 'Язык по умолчанию'),
	(120, 'ru', 'Theme list (space specarate)', 'Список тем (через пробел)'),
	(121, 'ru', 'Theme default', 'Тема по умолчанию'),
	(122, 'ru', 'Theme default in CS', 'Тема по умолчанию в CS'),
	(124, 'ru', 'Cookie Key', 'Cookie Ключ'),
	(125, 'ru', 'Generate', 'Генерировать'),
	(126, 'ru', 'General setting', 'Основные настройки'),
	(127, 'ru', 'Database', 'База данных'),
	(129, 'ru', 'Working with database', 'Работа с базой данных'),
	(130, 'ru', 'DB', 'База'),
	(131, 'ru', 'Tables', 'Таблицы'),
	(132, 'ru', 'Data', 'Данные'),
	(133, 'ru', 'Create', 'Создать'),
	(134, 'ru', 'Delete', 'Удалить'),
	(135, 'ru', 'Clear', 'Очистить'),
	(136, 'ru', 'Edit', 'Изменить'),
	(137, 'ru', 'Not connection to database', 'Нет подключения к базе данных'),
	(138, 'ru', 'File with tables not found', 'Файл с таблицами не существует'),
	(139, 'ru', 'File with data not found', 'Файл с данными не существует'),
	(140, 'ru', 'Global', 'Глобальные'),
	(141, 'ru', 'Local', 'Локальные'),
	(142, 'ru', 'Error', 'Ошибка'),
	(286, 'ru', 'Variable', 'Переменная'),
	(288, 'ru', 'Value', 'Значение'),
	(294, 'ru', 'Total', 'Всего'),
	(296, 'ru', 'Edit players', 'Редактировать игроков'),
	(300, 'ru', 'Admin', 'Админ'),
	(302, 'ru', 'Active', 'Активный'),
	(304, 'ru', 'Yes', 'Да'),
	(306, 'ru', 'No', 'Нет'),
	(308, 'ru', 'Not autorised', 'Пользователь не авторизован'),
	(310, 'ru', 'Access denied', 'Доспуп запещен'),
	(312, 'ru', 'Pages Not Found', 'Страница не существует'),
	(314, 'ru', 'Internal Server Error', 'Внутренняя ошибка сервера'),
	(316, 'ru', 'Download', 'Скачать'),
	(318, 'ru', 'Servers', 'Сервера'),
	(320, 'ru', 'Welcome to game server', 'Добро пожаловать на игровые сервера'),
	(322, 'ru', 'Lines in Achiev', 'Строк в Достижениях'),
	(324, 'ru', 'Bots', 'Боты'),
	(326, 'ru', 'OS', 'ОС'),
	(328, 'ru', 'Descriptor', 'Дескриптор'),
	(330, 'ru', 'Mod', 'Мод'),
	(332, 'ru', 'Frags', 'Очки'),
	(334, 'ru', 'Server not found', 'Сервер не найден'),
	(336, 'ru', 'Check', 'Проверить'),
	(338, 'ru', 'Language', 'Язык'),
	(340, 'ru', 'Edit servers', 'Изменить сервера'),
	(342, 'ru', 'Player not found', 'Игрок не найден'),
	(344, 'ru', 'Last Records on Kreedz', 'Последние рекорды на Kreedz'),
	(355, 'ru', 'Authorization', 'Авторизация'),
	(358, 'ru', 'Our Last Time', 'Последний заход'),
	(360, 'ru', 'Shared Online', 'Общий онлайн'),
	(364, 'ru', 'Wrong IP', 'Неправильный IP'),
	(366, 'ru', 'Wrong Steam Id, e.g. STEAM_#:#:#..#', 'Неправильный Steam Id, вид STEAM_#:#:#..#'),
	(368, 'ru', 'Wrong E-mail', 'Неправильный e-mail'),
	(370, 'ru', 'Activation link sent to your e-mail', 'Ссылка для активации отправлена на e-mail'),
	(372, 'ru', 'Reset Password', 'Произведен сброс пароля'),
	(374, 'ru', 'Kreedz', 'Прыжки'),
	(378, 'ru', 'Longjumps', 'Longjumps'),
	(380, 'ru', 'Records', 'Рекорды'),
	(382, 'ru', 'Archive', 'Архив'),
	(384, 'ru', 'LJ Records', 'LJ Рекорды'),
	(386, 'ru', 'Difficulty', 'Сложность'),
	(388, 'ru', 'Authors', 'Автор'),
	(390, 'ru', 'Date', 'Дата'),
	(392, 'ru', 'Distance', 'Дистанция '),
	(394, 'ru', 'Block', 'Блок '),
	(396, 'ru', 'Prestrafe', 'Престрейф '),
	(398, 'ru', 'Speed', 'Скорость'),
	(399, 'ru', 'Server Record', 'Рекорд сервера'),
	(400, 'ru', 'Check IP', 'Проверить IP');
/*!40000 ALTER TABLE `langs` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
